# Generated by Django 3.2.12 on 2023-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soilapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hour', models.CharField(max_length=220)),
                ('Temp', models.IntegerField()),
            ],
        ),
    ]
